#include <stdio.h>
//Question: Which number under 1e+6 produces the longest chain?
//Conditions, if n is even, n = n/2
//If n is odd, n = n*3 +1
//Keep making the chain til you get to 1
int main()
{
	unsigned int Collatz,i,Total_Length,Longest_Chain = 0,Collatz_Hold,Final_Collatz;
	for(i=3;i<1e+6;i+=2){			//I'm iterating in odd numbers because I believe an odd will produce the longest chain
		Collatz = i;
		Collatz_Hold = i;
		Total_Length = 0;
		while(Collatz != 1){	
			if(Collatz % 2 == 0){
				Collatz /= 2;
				Total_Length += 1;
			}
			else{
				Collatz = Collatz*3 + 1;
				Total_Length += 1;
			}
		}
		if(Total_Length > Longest_Chain){		//If the length of this one is greater than the current greatest length
			Longest_Chain = Total_Length;		//Than replace the value of greatest length with this one
			Final_Collatz = Collatz_Hold;		//Also replace the actual starting number associated with this length
		}
	}
	printf("The Longest chain is generated by %d\n",Final_Collatz);
	return 0;
}

		
